import sympy as sp

from sympy.parsing.sympy_parser import (
    convert_xor,
    implicit_multiplication_application,
    parse_expr,
    standard_transformations,
)


x = sp.symbols("x")
y = sp.symbols("y")
C = sp.symbols("C")


TRANSFORMATIONS = standard_transformations + (
    implicit_multiplication_application,
    convert_xor,
)


def normalize_answer(answer: str) -> str:
    answer = answer.strip()

    if answer.startswith("y="):
        answer = answer[2:].strip()

    elif answer.startswith("y ="):
        answer = answer[3:].strip()

    answer = answer.replace("X", "x")
    answer = answer.replace("×", "*")
    answer = answer.replace("÷", "/")

    # Allow lowercase c as integration constant.
    answer = answer.replace("c", "C")

    return answer


def parse_student_expression(expression: str):
    return parse_expr(
        expression,
        transformations=TRANSFORMATIONS,
        local_dict={
            "x": x,
            "y": y,
            "C": C,
            "exp": sp.exp,
            "e": sp.E,
        },
        evaluate=True,
    )


def build_separation_steps(
    rhs: sp.Expr,
) -> list[str]:
    """
    Build detailed explanation for equations of the form

        dy/dx = f(x) * y

    which is the family currently generated by separable.py.
    """

    # Extract f(x) from rhs = f(x) * y
    fx = sp.simplify(
        rhs / y
    )

    integrated_fx = sp.integrate(
        fx,
        x
    )

    return [
        (
            f"Start with the differential equation: "
            f"dy/dx = {sp.sstr(rhs)}."
        ),
        (
            "The right-hand side contains y multiplied by "
            "an expression involving x. This tells us the "
            "equation can be separated."
        ),
        (
            "Move y to the left side by dividing both sides by y."
        ),
        (
            f"This gives: (1/y) dy = "
            f"{sp.sstr(fx)} dx."
        ),
        (
            "Now the variables are separated: the left side "
            "contains only y and the right side contains only x."
        ),
        (
            "Integrate both sides."
        ),
        (
            f"Left side: integral(1/y) dy = ln|y|."
        ),
        (
            f"Right side: integral({sp.sstr(fx)}) dx "
            f"= {sp.sstr(integrated_fx)}."
        ),
        (
            f"So we obtain: "
            f"ln|y| = {sp.sstr(integrated_fx)} + C."
        ),
        (
            "To solve for y, exponentiate both sides."
        ),
        (
            f"This gives: "
            f"y = C*exp({sp.sstr(integrated_fx)})."
        ),
        (
            "The C here represents an arbitrary constant. "
            "The exponential of the previous integration constant "
            "can be absorbed into a new constant C."
        ),
    ]


def evaluate_separable_solution(
    student_answer: str,
    rhs_expression: str,
) -> dict:
    student_answer = normalize_answer(
        student_answer
    )

    try:
        student_solution = parse_student_expression(
            student_answer
        )

        rhs = parse_student_expression(
            rhs_expression
        )

    except (
        SyntaxError,
        TypeError,
        ValueError,
        NameError,
        sp.SympifyError,
    ):
        return {
            "correct": False,
            "core_correct": False,
            "missing_constant": False,
            "parse_error": True,
            "error_type": "parse_error",
            "feedback": (
                "I could not understand the mathematical expression."
            ),
            "steps": [
                "You may write multiplication as 3x or 3*x.",
                "You may write powers as x^2 or x**2.",
                "For exponentials you may write exp(x^2).",
                "For example: C*exp(3*x^2/2).",
            ],
        }

    if not isinstance(
        student_solution,
        sp.Expr
    ):
        return {
            "correct": False,
            "core_correct": False,
            "missing_constant": False,
            "parse_error": True,
            "error_type": "parse_error",
            "feedback": (
                "I could not understand the mathematical expression."
            ),
            "steps": [],
        }

    #
    # Student proposes:
    #
    #     y = g(x)
    #
    # Differentiate it to obtain the left-hand side.
    #
    lhs = sp.diff(
        student_solution,
        x
    )

    #
    # Substitute student's y(x) into the right-hand side
    # of the original differential equation.
    #
    rhs_with_solution = rhs.subs(
        y,
        student_solution
    )

    residual = sp.simplify(
        lhs - rhs_with_solution
    )

    satisfies_ode = (
        residual == 0
    )

    student_has_constant = (
        C in student_solution.free_symbols
    )

    if (
        satisfies_ode
        and student_has_constant
    ):
        return {
            "correct": True,
            "core_correct": True,
            "missing_constant": False,
            "parse_error": False,
            "error_type": None,
            "feedback": (
                "Correct. Your proposed function satisfies "
                "the differential equation."
            ),
            "steps": [],
        }

    if (
        satisfies_ode
        and not student_has_constant
    ):
        return {
            "correct": False,
            "core_correct": True,
            "missing_constant": True,
            "parse_error": False,
            "error_type": "missing_constant",
            "feedback": (
                "Your function satisfies the differential equation, "
                "but it represents only one particular solution. "
                "The general solution needs an arbitrary constant C."
            ),
            "steps": [
                (
                    "Your mathematical form is correct."
                ),
                (
                    "However, solving an ODE without an initial "
                    "condition normally gives a family of solutions."
                ),
                (
                    "That family is represented using an arbitrary "
                    "constant C."
                ),
                (
                    "For example, write the solution in the form "
                    "y = C*exp(...)."
                ),
            ],
        }

    return {
    "correct": False,
    "core_correct": False,
    "missing_constant": False,
    "parse_error": False,
    "error_type": "incorrect_solution",
    "feedback": (
        "Your proposed function does not satisfy the differential "
        "equation. Let's work through the concepts one step at a time."
    ),
    "steps": [],
}